# Generated by Django 4.2.3 on 2023-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(default=[], to='shop.order'),
        ),
    ]
