# Generated by Django 4.2.3 on 2023-08-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField(max_length=9999)),
                ('address2', models.TextField(max_length=9999)),
                ('city', models.CharField(max_length=999)),
                ('province', models.CharField(max_length=2)),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
