# Generated by Django 4.2.3 on 2023-09-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_address_order_dob_order_email_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
    ]
