# Generated by Django 4.2.3 on 2023-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=None, max_length=17),
            preserve_default=False,
        ),
    ]
