# Generated by Django 4.2.3 on 2023-09-19 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('has_variants', models.BooleanField(default=False)),
                ('require_contact', models.BooleanField(default=False)),
                ('price_text', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='flowers.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flower_media')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HeadCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
                ('display_photo', models.URLField(default='https://drive.google.com/uc?export=view&id=1qZOythbdopUd6AW-QCk6rIcpxK81C9gv')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower', to='flowers.flower')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='flower',
            name='default_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='flowers.flowervariant'),
        ),
        migrations.AddField(
            model_name='flower',
            name='media',
            field=models.ManyToManyField(to='flowers.flowermedia'),
        ),
        migrations.AddField(
            model_name='category',
            name='head_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.headcategory'),
        ),
    ]
