# Generated by Django 4.2.2 on 2023-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='flowers',
            field=models.ManyToManyField(to='flowers.flower'),
        ),
    ]
