# Generated by Django 4.2.3 on 2023-09-19 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowervariant',
            name='external_id',
        ),
        migrations.AddField(
            model_name='flower',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
