# Generated by Django 4.2.3 on 2023-07-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_headcategory_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headcategory',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='category',
            name='head_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.headcategory'),
        ),
    ]
