# Generated by Django 4.2.3 on 2023-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_remove_headcategory_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcategory',
            name='display_photo',
            field=models.URLField(default='https://drive.google.com/uc?export=view&id=1qZOythbdopUd6AW-QCk6rIcpxK81C9gv'),
        ),
    ]
