# Generated by Django 4.2.3 on 2023-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_alter_flowervariant_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowermedia',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
