# Generated by Django 4.2.3 on 2023-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_flower_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
