# Generated by Django 4.2.3 on 2023-09-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_alter_flowermedia_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='default_variant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_flower', to='flowers.flowervariant'),
        ),
    ]
