# Generated by Django 4.2.3 on 2023-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_alter_flower_default_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flower',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
