# Generated by Django 4.2.3 on 2023-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_flower_variant_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='variant_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
