# Generated by Django 4.2.3 on 2023-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_flower_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='variant_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='flowers.flower'),
        ),
    ]
