# Generated by Django 4.2.3 on 2023-10-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_category_hidden_flower_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowervariant',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='flowers.flowermedia'),
        ),
    ]
