# Generated by Django 4.2.3 on 2023-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_alter_flower_variant_name_alter_flower_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='variants',
            field=models.ManyToManyField(blank=True, to='flowers.flower'),
        ),
    ]
