# Generated by Django 4.2.3 on 2023-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_alter_flower_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
