# Generated by Django 4.2.3 on 2023-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_alter_flower_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
