# Generated by Django 4.2.3 on 2024-02-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_remove_headcategory_display_image_flower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='default_variant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_flower', to='flowers.flowervariant'),
        ),
    ]
