# Generated by Django 4.2.3 on 2023-08-22 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0012_alter_flower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
