# Generated by Django 4.2.3 on 2023-08-23 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0013_alter_flower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
