# Generated by Django 4.2.3 on 2023-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0015_alter_flower_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='external_id',
            field=models.CharField(default='98a678e9499f401b8fd80ac2edde3072', editable=False, max_length=40, unique=True),
        ),
    ]
