# Generated by Django 4.2.3 on 2023-08-26 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0016_alter_flower_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
