# Generated by Django 4.2.3 on 2023-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0018_flower_require_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='require_contact',
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
