# Generated by Django 4.2.3 on 2023-08-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0019_remove_flower_require_contact_alter_flower_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='require_contact',
            field=models.BooleanField(default=False),
        ),
    ]
