# Generated by Django 4.2.3 on 2023-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0020_flower_require_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='price_text',
            field=models.CharField(default='', max_length=99999),
        ),
    ]
