# Generated by Django 4.2.3 on 2023-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
